### ISSUE TITLE
set up automatic deployment of landing page to staging

### ISSUE THREAD

**Issue by afeld** [18F/cg-landing#75]
...in GovCloud, at least. Follow-up to https://github.com/18F/cg-landing/pull/74.
## Acceptance criteria
- [ ] Site is automatically deployed to staging when a change lands in `master`
## TODOs
- [x] Get staging credentials
- [ ] Create deployer user in staging
- [ ] Tweak pipeline to deploy to staging
- [ ] Successfully deploy to staging

**Comment by cnelson** [comment]
This is being handled as part of combining `cg-docs` and `cg-site`
